services:
  web:
    image: nginx:latest
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
  app:
    build:
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./app:/var/www/html/
    depends_on:
      - db
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    restart: unless-stopped
volumes:
  db_data: {}